name: ODS3
description: "Marque o mais importante."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  permission_handler: ^12.0.1
  firebase_messaging: ^16.0.4
  timezone: ^0.10.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true